default: &default
  adapter: postgresql
  encoding: unicode  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  # username: postgres
  # password: daniel

development:
  <<: *default
  database: league_system_pro_development

test:
  <<: *default
  database: league_system_pro_test

production:
  primary: &primary_production
    <<: *default
    database: league_system_pro_production
    username: railsapps
    password: <%= Rails.application.credentials.dig(:production, :database_password) %>    
  cache:
    <<: *primary_production
    database: league_system_pro_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: league_system_pro_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: league_system_pro_production_cable
    migrations_paths: db/cable_migrate
